version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodbctr"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongo-img:1.0
    container_name: springboot-mongo-ctr
    ports:
      - 8080:8080
    links:
      - mongodb